### ISSUE TITLE
Bypass 001: IE10 using 1..constructor.constructor

### ISSUE THREAD

**Issue by x00mario** [natevw/evel#10]
https://tinyurl.com/evel-bypass-01

I think this is somewhere between sandbox- and browser-bug. Technically, a fresh window should not be available in this scope.

**Comment by natevw** [comment]
Thanks, good catch! I'll be reviewing this soon, especially if #11 can be avoided.

Expanded URL:
http://natevw.github.io/evel/challenge.html#1..constructor.constructor('top.alert(window)')()
