### ISSUE TITLE
Bypass 003: Indirect eval call

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [natevw/evel#19]
Hey everyone,

I'm not sure how active this project is anymore since the last bypass was found, but I wanted to report a vulnerability anyway.

Here's how it works : 

`(1,eval)._global.alert('bypassing evel !')`

Since `(1,eval)()` is an an indirect call to eval, it can get a context and access the `evel` object.

For more info about this type of calls you can check this awesome article :

http://perfectionkills.com/global-eval-what-are-the-options/#indirect_eval_call_theory

**Comment by natevw** [comment]
Ah, great catch! All previous bypasses were actually fixed so I'm very glad you reported this.

This is an artefact of how we are handling internal helpers. It used to be that the evel module itself was masked along with every other non-JS global, and so some helper stuff was let to hang around off the `evel` function/namespace. But to patch the _original_ "indirect eval" vulnerabilty we inadvertently exposed this "namespace" by [providing it in place of the builtin eval](https://github.com/natevw/evel/blob/c11bcc92e92898d5471d43e840a0c19c13555850/evel.js#L88)!

So I'm hopeful this can be a relatively straightfoward fix, should just require some refactoring of how our code is structured to avoid this type of exposure.

**Comment by kumavis** [comment]
to clarify, the following are equivalent when run through `evel`

``` javascript
(1,eval)._global.alert('bypassing evel !');
eval._global.alert('bypassing evel !');
```

**Comment by natevw** [comment]
Thanks again for reporting this! Should be fixed now…back to no more known vulnerabilities and regression tests to "prove" it ;-)
