### ISSUE TITLE
infinite loops

### ISSUE THREAD

**Issue by dominictarr** [natevw/evel#5]
`while(true);` or regexps that abuse lookahead to get exponential execution times?

**Comment by dominictarr** [comment]
hmm, maybe you can statically analyse for those?

Or, you could add counters to dangerous looking code,
and throw if it held the event loop too long?

Such a method would probably have to reject code a little over zealously,
because of the halting problem...

**Comment by tsuckow** [comment]
If using an iframe to isolate the code, could you specify a maximum
execution time and kill the iframe? Though if doing that, why not web
worker.

**Comment by dominictarr** [comment]
This project my be relevant to using webworkers for isolation:
https://github.com/grimwire/grimwire

**Comment by natevw** [comment]
Thanks @dominictarr, good catch! I'm updating the README to add this.

The trouble with DoS-proof isolation in JS is that it has to use async communication. While this is commonly possible, some things are just not architected for that. In my case I need to [relatively] safely get return values from _untrusted_ code via _someone else's_ code which doesn't normally have use for the extra complexity of robust "separate thread" solutions.

The static analysis stuff seems to be in line with what [Google Caja](https://developers.google.com/caja/) sounds like it does. This is aiming for something a lot lighter weight — even if the way it masks globals is kind of ridiculously _not_ without overhead.
