### ISSUE TITLE
use safe-regexp

### ISSUE THREAD

**Issue by dominictarr** [natevw/evel#7]
@substack has just implemented a regexp filter that limits dangerous regexps.

https://github.com/substack/safe-regex

(we've also been discussing running restricted js for user leveldb queries)

**Comment by natevw** [comment]
Thanks for the tip. Even though it's cool work, I'm thinking I might close this as "will not fix" on this library though.

Rationale: it doesn't do much for the even simpler case of (potentially obfuscated or truly undecidable) infinite loops using control flow. So using safe-regexp here seems to add complexity without any overall gain.

Completely solving the lock-up problem is beyond the scope of what I want to explore, personally. In my opinion the right way to solve true "safe execution" is sandboxing (e.g. `evel` if it stands up to review) _and_ an asyncronous process-like model (e.g. iframe/webworker/ via postMessage or even serverside). The former to avoid unwanted I/O, the latter to avoid complete denial of CPU.

**Comment by dominictarr** [comment]
fair enough.
